// OpoPoint — base de datos de Policía Local Andalucía
// Revisión: 24/08/2026
// Fuente de detección: OpoBusca. Los campos oficiales se marcan cuando se ha localizado BOE/BOJA/BOP.
// NO interpretar "Seguimiento" como convocatoria abierta: significa que el plazo no está confirmado en esta carga.

const convocatoriasOpoPoint = [
  {
    "id": "opopoint-001-aznalcollar",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Aznalcollar",
    "municipio": "Aznalcollar",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "24/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-002-villafranca-de-cordoba",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Villafranca de Córdoba",
    "municipio": "Villafranca de Córdoba",
    "provincia": "Córdoba",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "20/08/2026",
    "fechaInicio": "21/08/2026",
    "fechaFin": "17/09/2026",
    "estado": "En plazo",
    "boe": "BOE-A-2026-17980",
    "boeUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17980",
    "bojaUrl": "https://www.juntadeandalucia.es/eboja/2026/152/39",
    "bop": "BOP Córdoba nº 138, 20/07/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-003-alcala-del-rio",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Alcalá del Río",
    "municipio": "Alcalá del Río",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 4,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "17/08/2026",
    "fechaInicio": "17/08/2026",
    "fechaFin": "11/09/2026",
    "estado": "En plazo",
    "boe": "BOE-A-2026-17786",
    "boeUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17786",
    "bojaUrl": "https://www.juntadeandalucia.es/eboja/2026/151/s57",
    "bop": "BOP Sevilla nº 143, 27/07/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-004-estepa",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Estepa",
    "municipio": "Estepa",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 8,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "17/08/2026",
    "fechaInicio": "18/08/2026",
    "fechaFin": "14/09/2026",
    "estado": "En plazo",
    "boe": "BOE-A-2026-17861",
    "boeUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17861",
    "bojaUrl": "https://www.juntadeandalucia.es/eboja/2026/154/35",
    "bop": "BOJA nº 154, 11/08/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-005-dos-torres",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Dos Torres",
    "municipio": "Dos Torres",
    "provincia": "Córdoba",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "14/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-006-la-puebla-del-rio",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de La Puebla del Río",
    "municipio": "La Puebla del Río",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "14/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-007-lanjaron",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Lanjarón",
    "municipio": "Lanjarón",
    "provincia": "Granada",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "12/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-008-albox",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Albox",
    "municipio": "Albox",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "11/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "En plazo",
    "boe": "BOE-A-2026-17540",
    "boeUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17540",
    "bojaUrl": null,
    "bop": "BOP Almería nº 130, 09/07/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-009-marbella",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Marbella",
    "municipio": "Marbella",
    "provincia": "Málaga",
    "grupo": "C1",
    "plazas": 11,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "11/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-010-osuna",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Osuna",
    "municipio": "Osuna",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "07/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-011-mojacar",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Mojácar",
    "municipio": "Mojácar",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "04/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-012-palomares-del-rio",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Palomares del Río",
    "municipio": "Palomares del Río",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "03/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "En plazo",
    "boe": "BOE-A-2026-16791",
    "boeUrl": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-16791",
    "bojaUrl": "https://www.juntadeandalucia.es/eboja/2026/140/59-verificacion",
    "bop": "BOP Sevilla nº 103, 01/06/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-013-cuevas-del-almanzora",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Cuevas del Almanzora",
    "municipio": "Cuevas del Almanzora",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "03/08/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-014-olula-del-rio",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Olula del Río",
    "municipio": "Olula del Río",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "31/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-015-motril",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Motril",
    "municipio": "Motril",
    "provincia": "Granada",
    "grupo": "C1",
    "plazas": 5,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "31/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-016-la-mojonera",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de La Mojonera",
    "municipio": "La Mojonera",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "28/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-017-berja",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Berja",
    "municipio": "Berja",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 4,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "27/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": "https://www.juntadeandalucia.es/eboja/2026/138/48-verificacion",
    "bop": "BOJA nº 138, 20/07/2026",
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Oficial localizada"
  },
  {
    "id": "opopoint-018-marchena",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Marchena",
    "municipio": "Marchena",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "24/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-019-cartaya",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Cartaya",
    "municipio": "Cartaya",
    "provincia": "Huelva",
    "grupo": "C1",
    "plazas": 11,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "22/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-020-hinojos",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Hinojos",
    "municipio": "Hinojos",
    "provincia": "Huelva",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "22/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-021-almunecar",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Almuñécar",
    "municipio": "Almuñécar",
    "provincia": "Granada",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "20/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-022-algeciras",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Algeciras",
    "municipio": "Algeciras",
    "provincia": "Cádiz",
    "grupo": "C1",
    "plazas": 14,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "20/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-023-espartinas",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Espartinas",
    "municipio": "Espartinas",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "15/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-024-espartinas",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Espartinas",
    "municipio": "Espartinas",
    "provincia": "Sevilla",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "08/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-025-montoro",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Montoro",
    "municipio": "Montoro",
    "provincia": "Córdoba",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "08/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-026-baeza",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Baeza",
    "municipio": "Baeza",
    "provincia": "Jaén",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "06/07/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-027-agencia-publica-de-puertos-de-andalucia",
    "puesto": "Policía Local",
    "organismo": "Agencia Pública de Puertos de Andalucía",
    "municipio": "Ámbito Andalucía",
    "provincia": "Andalucía",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "30/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-028-ubrique",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Ubrique",
    "municipio": "Ubrique",
    "provincia": "Cádiz",
    "grupo": "C1",
    "plazas": 4,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "22/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-029-loja",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Loja",
    "municipio": "Loja",
    "provincia": "Granada",
    "grupo": "C1",
    "plazas": 5,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "22/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-030-trebujena",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Trebujena",
    "municipio": "Trebujena",
    "provincia": "Cádiz",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "16/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-031-jabugo",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Jabugo",
    "municipio": "Jabugo",
    "provincia": "Huelva",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "09/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-032-cadiz",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Cádiz",
    "municipio": "Cádiz",
    "provincia": "Cádiz",
    "grupo": "C1",
    "plazas": 11,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "09/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-033-moguer",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Moguer",
    "municipio": "Moguer",
    "provincia": "Huelva",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "08/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-034-maracena",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Maracena",
    "municipio": "Maracena",
    "provincia": "Granada",
    "grupo": "C1",
    "plazas": 2,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "03/06/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-035-pedro-abad",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Pedro Abad",
    "municipio": "Pedro Abad",
    "provincia": "Córdoba",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "28/05/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-036-roquetas-de-mar",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Roquetas de Mar",
    "municipio": "Roquetas de Mar",
    "provincia": "Almería",
    "grupo": "C1",
    "plazas": 4,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "26/05/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-037-istan",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Istán",
    "municipio": "Istán",
    "provincia": "Málaga",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "24/04/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-038-benameji",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Benamejí",
    "municipio": "Benamejí",
    "provincia": "Córdoba",
    "grupo": "C1",
    "plazas": 3,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "22/04/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  },
  {
    "id": "opopoint-039-villarrasa",
    "puesto": "Policía Local",
    "organismo": "Ayuntamiento de Villarrasa",
    "municipio": "Villarrasa",
    "provincia": "Huelva",
    "grupo": "C1",
    "plazas": 1,
    "turno": "Libre / por verificar",
    "sistema": "Oposición / por verificar",
    "fechaPublicacion": "20/04/2026",
    "fechaInicio": null,
    "fechaFin": null,
    "estado": "Seguimiento",
    "boe": null,
    "boeUrl": null,
    "bojaUrl": null,
    "bop": null,
    "fuente": "OpoBusca",
    "fuenteUrl": "https://www.opobusca.com/oposiciones/policia-local-andalucia",
    "verificacion": "Pendiente de contraste oficial"
  }
];

const datos = convocatoriasOpoPoint;
const convocatorias = convocatoriasOpoPoint;

if (typeof window !== "undefined") {
  window.convocatoriasOpoPoint = convocatoriasOpoPoint;
  window.datos = convocatoriasOpoPoint;
  window.convocatorias = convocatoriasOpoPoint;
}
